#ifndef ERROR_H
# define ERROR_H

# define ERROR_GENERAL "\033[1;31mError: $MSG !\n\033[0m"
# define BAD_ALLOC "Unable to allocate memory"
# define BAD_ARGC "Invalid argument count"
# define BAD_FEMPTY "Scene description file is mandatory"
# define BAD_FILE "Invalid config file"
# define BAD_MAP "Invalid map"
# define EMPTY_MAP "Invalid empty map"
# define EMPTY_CONF "Invalid empty config"
# define ERROR_EXTA "Invalid file extension"
# define ERROR_FORMAT "Invalid texture format support : {path, #hex, argb(,,,) '0-255,0-255,0-255'}"
# define ERROR_HEXA "Invalid hexa color, it shoud be #RRGGBB"
# define ERROR_RGBA "Invalid rgba color, it shoud be rgba (xxx,xxx,xxx)"
# define ERROR_TXT "texture was not set"
# define BAD_E_LINE "Empty Line within the map"
# define BAD_C_LINE "Map line should contain only {1, 0, E, W, S, N, ' '}"
# define BAD_D_LINE "Player can face one and only one direction {S, N, E, W}"
# define BAD_C_MAP "Map has to be closed with walls, a.k.a {1}"
# define BAD_P_MAP "Make no sense to have empty space in path"
# define ERROR_DUP "$TXT Duplicate texture"
# define ERROR_ITXT "$TXTWall Texture can only be image format"
# define ERROR_CTXT "$TXTsky and floor can only be solid color"
#endif
